club/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    # path('about', views.about, name='about'),
    path('faq', views.faq, name='faq'),
    path('conduct', views.conduct, name='conduct'),
    path('events/', views.event_index, name='events'),
    path('projects/', views.project_index, name='projects'),
    path('updates/', views.update_index, name='updates'),
    path('updates/<int:update_id>', views.update_detail, name='update_detail'),
    path('events/<int:event_id>', views.event_detail, name='event_detail'),
    path('events/<int:event_id>/planning', views.event_planning, name='event_planning'),
    path('events/<int:event_id>/rsvp', views.event_rsvp, name='event_rsvp'),
    path('events/<int:event_id>/attendance', views.event_attendance, name='event_attendance'),
    path('events/<int:event_id>/feedback', views.event_feedback, name='event_feedback'),
    path('members/', views.member_index, name='members'),
    path('members/<int:member_id>', views.member_detail, name='member_detail'),
    path('core-team/', views.core_team, name='core_team'),
    path('core-team/email', views.core_team_email, name='core_team_email'),
    path('core-team/roadmap', views.roadmap_index, name='roadmap'),
    path('core-team/social-media', views.social_media, name='social_media'),
    path('core-team/member-management', views.member_management, name='member_management'),
    path('core-team/<str:role_name>', views.core_team_role, name='core_team_role'),
    path('account/', views.user_account, name='user_account'),
    path('account/verify', views.verify_account, name='verify_account')
]

dsc_portal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('club.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
]

club/models.py
import requests

from .logger import logger
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.db.models.signals import pre_save, post_save, pre_delete, post_delete
from .email import send_templated_email
from random import choice
from string import ascii_uppercase

from .google_api import docs_service, drive_service, slides_service, calendar_service
from django.utils import timezone


class SkillTagManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(tag_type='S')

class DietaryRestrictionTagManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(tag_type='D')

class Tag(models.Model):
    TAG_TYPE_CHOICES = [
        ('D', 'Dietary Restriction'),
        ('S', 'Skill')
    ]
    tag_type = models.CharField(max_length=5, choices=TAG_TYPE_CHOICES, help_text='The type of tag.')
    title = models.CharField(max_length=50, help_text='The title of the tag.')

    objects = models.Manager()
    skills = SkillTagManager()
    dietary_restrictions = DietaryRestrictionTagManager()

    def __str__(self):
        return f'{self.get_tag_type_display()}: {self.title}'
    
    class Meta:
        ordering = ['tag_type', 'title']


class SchoolYear(models.Model):
    '''A SchoolYear represents a full year of school...'''
    start_date = models.DateField(help_text='The first day of the school year.')
    end_date = models.DateField(help_text='The last day of the school year.')

    @property
    def is_ongoing(self):
        return self.start_date <= timezone.now().date() <= self.end_date
    
    @property
    def title(self):
        return f'{self.start_date.month}/{str(self.start_date.year)[2:]}-{self.end_date.month}/{str(self.end_date.year)[2:]}'

    @classmethod
    def get_current_school_year(cls):
        now = timezone.now().date()
        return SchoolYear.objects.get(start_date__gte=now, end_date__gte=now)

    def __str__(self):
        return f'School Year {self.title}'

class VerifiedMemberManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(verified=True)

class Member(models.Model):
    '''
    Member represents a club member, an extension of the base user model.
    This holds club member info such as school grade and dietary restrictions.
    '''
    objects = models.Manager()
    verified_members = VerifiedMemberManager()

    user = models.OneToOneField(User, on_delete=models.CASCADE, null=False)

    school_username = models.CharField(max_length=100, blank=True, null=True, help_text='The username of the student/faculty member of the school.')
    
    @property
    def school_email(self):
        return self.school_username + settings.SCHOOL_EMAIL_SUFFIX

    verification_code = models.CharField(blank=True, null=True, max_length=100, help_text='The randomly generated code sent to the user\'s school email to verify it.')

    verified = models.BooleanField(default=False, help_text='Whether the user has verified their school username or not. True means that they are a real club member.')

    profile_image = models.ImageField(blank=True, null=True, upload_to='profile-images')

    @property
    def profile_image_url(self):
        ''''''
        if self.profile_image:
            return self.profile_image.url
        else:
            return 'https://bulma.io/images/placeholders/1280x960.png'

    GRADE_TYPES = [
        ('Fr', 'Freshman'),
        ('So', 'Sophomore'),
        ('Ju', 'Junior'),
        ('Se', 'Senior'),
        ('G', 'Graduate'),
        ('F', 'Faculty')
    ]
    grade = models.CharField(max_length=2, blank=True, null=True, choices=GRADE_TYPES, help_text='The grade of the student (or faculty status)')
    # dietary_restrictions = ???
    # TODO: make an tag system for dietary restrictions to easily query

    bio = models.TextField(max_length=2000, blank=True, null=True, help_text='A short bio about the member which will be public.')

    tags = models.ManyToManyField(Tag, blank=True, related_name='members')

    @property
    def group_names(self):
        if self.user.groups.count() > 0:
            return ' & '.join(self.user.groups.values_list('name',flat = True))
        return 'Core Team Member'

    def skills(self):
        return self.tags.filter(tag_type='S')
    
    def dietary_restrictions(self):
        return self.tags.filter(tag_type='D')

    def verify(self):
        self.verified = True
        self.verification_code = None
        logger.info(f'User {self.user} verified their account.')

        # Invite to Slack
        requests.post('https://slack.com/api/users.admin.invite', data={
            'email': self.user.email,
            'token': settings.LEGACY_SLACK_TOKEN,
            # 'channels': ''
        })

    def __str__(self):
        return f'{self.user.get_full_name()} ({self.user.email})'

    @classmethod
    def post_user_save(cls, sender, instance, created, *args, **kwargs):
        if created:
            # Send welcome email on first login (user creation)
            data = {
                'user': instance,
                'website': settings.DOMAIN,
                'school_name_short': settings.SCHOOL_NAME_SHORT
            }
            return send_templated_email('Welcome to DSC!', 'new_user', data, [instance.email])

        try:
            has_member = instance.member is not None
        except:
            instance.member = Member()
            instance.member.save()
post_save.connect(Member.post_user_save, sender=settings.AUTH_USER_MODEL)


class PublicEventManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(hidden=False).exclude(event_type='CT')

class Event(models.Model):
    '''Events represent one-time club meetings.'''

    objects = models.Manager()
    public_events = PublicEventManager()

    # Recognized types of events
    # Taken from https://sites.google.com/google.com/developerstudentclubleads/dsc-activities-reporting
    EVENT_TYPES = [
        ('IS', 'Info Session'),
        ('SJ', 'Study Jam'),
        ('OH', 'Office Hours'),
        ('HO', 'Hands-on Workshop'),
        ('HA', 'Hackathon'),
        ('SS', 'Speaker Session'),
        ('SC', 'Showcase'),
        ('CT', 'Core Team Meeting')
    ]

    event_type = models.CharField(max_length=2, choices=EVENT_TYPES, help_text='Whether the event is a Workshop, Info session, etc.')
    
    @property
    def is_publicly_visible(self):
        return self.event_type != 'CT' and not self.hidden

    hidden = models.BooleanField(default=False, help_text='If true then the event will not be shown anywhere. Use this to create event drafts.')

    # Title of Event limited to 100 characters
    title = models.CharField(max_length=100, help_text='The headline title of the event. Should be very concise.')
    
    # (Optional) Event tagline
    tagline = models.CharField(max_length=200, blank=True, null=True, help_text='An optional tagline that will be displayed with the event title if it exists.')
    
    # Required event description
    description = models.TextField(max_length=10000, help_text='Long descriptionf of the event. Supports Markdown.')

    what_to_bring = models.CharField(max_length=500, blank=True, null=True, help_text='An optional description of items members should bring, e.g. laptop and notebook')

    review = models.TextField(max_length=10000, blank=True, null=True, help_text='A review after the event concludes covering how the event went, turn out, issues faced, etc. for future leaders to read and take into account.')

    # Date and time range of event
    start = models.DateTimeField(help_text='The exact start date and time of the event.')
    end = models.DateTimeField(help_text='The exact end date and time of the event.')

    location = models.CharField(max_length=100, help_text='Where the event is being held.')

    @property
    def full_location(self):
        return self.location + settings.SCHOOL_LOCATION_SUFFIX

    attendance_code = models.CharField(max_length=6, blank=True, null=True, help_text='Random attendance code for members to submit to verify their attendance.')

    slideshow_id = models.CharField(max_length=300, blank=True, null=True, help_text='(optional) The ID of the Google Slides slideshow.')

    thumbnail_link = models.URLField(max_length=500, blank=True, null=True, help_text='An optional link to an image to show for the event. If a slideshow is associated with the event, it will automatically use the slide thumbnail.')

    meeting_notes_id = models.CharField(max_length=300, blank=True, null=True, help_text='The ID of the Google Docs meeting notes. This is most likely to an auto-generated Google Docs.')

    # PLANNING
    registered_with_google = models.BooleanField(default=False)
    sent_club_email = models.BooleanField(default=False)
    advertised_on_social_media = models.BooleanField(default=False)
    recorded_session = models.BooleanField(default=False)
    took_photos = models.BooleanField(default=False)
    reported_to_google = models.BooleanField(default=False)
    posted_review_to_social_media = models.BooleanField(default=False)

    @property
    def meeting_notes_link(self):
        '''A direct link to the Google Doc meeting notes generated for the event.'''
        return 'https://docs.google.com/document/d/' + self.meeting_notes_id

    @property
    def slideshow_link(self):
        '''A direct link to the Google Slides slideshow generated or chosen for the event.'''
        return 'https://docs.google.com/presentation/d/' + self.slideshow_id

    @property
    def has_started(self):
        now = timezone.now()
        return now >= self.start
    
    @property
    def is_ongoing(self):
        now = timezone.now()
        return self.start <= now <= self.end
    
    @property
    def is_over(self):
        now = timezone.now()
        return self.end < now

club/forms.py
from django.conf import settings
from django import forms

from .models import Member, Tag, EventFeedback

class MemberAccountForm(forms.Form):
    first_name = forms.CharField(label='First Name', max_length=200)
    last_name = forms.CharField(label='Last Name', max_length=200)
    school_username = forms.CharField(label=f'{settings.SCHOOL_NAME_SHORT} Username', max_length=100)
    grade = forms.ChoiceField(label='Grade', widget=forms.RadioSelect, choices=Member.GRADE_TYPES)
    bio = forms.CharField(widget=forms.Textarea, max_length=2000, label='Bio', required=False)
    skills = forms.ModelMultipleChoiceField(queryset=Tag.skills.all(), widget=forms.CheckboxSelectMultiple, label='I have experience in', required=False)
    dietary_restrictions = forms.ModelMultipleChoiceField(queryset=Tag.dietary_restrictions.all(), widget=forms.CheckboxSelectMultiple, label='My dietary preferences/restrictions are', required=False)
    profile_image = forms.ImageField(required=False)

class EventFeedbackForm(forms.ModelForm):

    class Meta:
        model = EventFeedback
        exclude = ['event', 'user', 'created_at', 'updated_at']

club/templates/club/events/detail.html
{% extends "club/base.html" %}
{% load markdown_filter %}
{% block head %}
<style>
    .slideshow-thumbnail {
        height: 200px;
    }

    .is-sticky {
        position: sticky;
        top: 70px;
    }

    @media screen and (max-width: 768px) {
        .is-reversed-mobile {
            display: flex;
            flex-direction: column-reverse;
        }
    }

    .event-info > div {
        margin-bottom: 10px;
    }

    .event-agenda li {
        list-style: none;
    }

    .event-agenda-description:not(:last-child) {
        margin-bottom: 10px;
    }
</style>
{% endblock %}
{% block content %}
<section class="section event-detail">
    <div class="container">
        {% include 'club/includes/messages.html' %}

        {% if event.hidden %}
        <div class="notification is-warning"><strong>HIDDEN EVENT</strong> This event is not public or listed on the
            events page yet.</div>
        {% endif %}

        <div class="columns is-reversed-mobile">
            <div class="column">
                <header>
                    <h1 class="title event-title is-size-2">{{ event.title }}</h1>
                    <h2 class="subtitle has-text-grey is-size-4">
                        {% if event.is_ongoing %}Ongoing{% endif %} {{ event.get_event_type_display }}
                    </h2>
                    {% if event.meeting_notes_id %}
                    <a href="{{ event.meeting_notes_link }}" target="_blank" class="event-meeting-notes">
                        <span class="icon">
                            <i class="fas fa-file-alt"></i>
                        </span>
                        <span>Meeting Notes</span>
                    </a>
                    {% endif %}
                </header>
                
                <div class="content">
                    <blockquote>
                        <p class="event-description">{{ event.description|markdown_filter|safe }}</p>
                    </blockquote>

                </div>
            </div>
            <div class="column is-4">
                <div class="is-sticky">

                    {% include "club/events/includes/event_info.html" %}

                    {% if event.slideshow_id %}
                    <figure style="position: relative" class="image">
                        {% if user.is_staff %}
                        <a title="Change slideshow" href="?select-slideshow=1" class="button"
                            style="position: absolute; top: 2px; right: 2px;">
                            <span class="icon">
                                <i class="fas fa-pencil-alt"></i>
                            </span>
                        </a>
                        {% endif %}
                        <a target="_blank" href="{{ event.slideshow_link }}">
                            <img class=" slideshow-thumbnail" src="{{ event.thumbnail_link }}"
                                alt="Thumbnail of event slideshow">
                        </a>
                    </figure>
                    {% endif %}
                </div>

            </div>
            {% if show_slideshows %}
            {% include "club/events/includes/event_select_slideshow_modal.html" %}
            {% endif %}
        </div>
        {% if user.is_authenticated %}
        {% if user.is_staff %}
        <hr>
        {% include "club/events/includes/event_staff_actions.html" %}
        {% elif event.is_ongoing and show_submit_attendance %}
        {% include "club/events/includes/event_attendance_modal.html" %}
        {% endif %}
        
        {% if event.is_over and show_submit_feedback  %}
        {% include "club/events/includes/event_feedback_modal.html" %}
        {% endif %}

        {% if user.is_staff and event.has_started %}
        <hr>
        <h2 class="subtitle">Event Review</h2>
        <form method="POST" onsubmit="return confirm('Make sure you have submitted the official DSC Report Form first!')">
            {% csrf_token %}
            <textarea class="input" name="review" id="event-review"
                placeholder="How did the event go? In particular, what issues did you face? How can you avoid similar mistakes in the future? How was feedback?">{% if event.review %}{{ event.review }}{% endif %}</textarea>
            <a target="_blank" href="https://bit.ly/reportdsc" class="button">Submit Official Report Form</a>
            <button type="submit" class="button is-success">{% if event.review %}Update{% else %}Save{% endif %}
                Review</button>
        </form>
        {% elif user.is_staff and event.event_type == 'SJ' %}
        <a target="_blank" href="https://bit.ly/csj_19" class="button is-link">
            <span class="icon">
                <i class="fas fa-cloud"></i>
            </span>
            <span>Register Cloud Study Jam</span>
        </a>
        {% endif %}
        <hr>
        {% endif %}

        <div class="buttons">
            {% if user.is_authenticated %}
            {% if user.is_staff and not event.meeting_notes_id %}
            <form method="POST" onsubmit="return confirm('Generate meeting notes in the Google Drive?')">
                {% csrf_token %}
                <input type="hidden" name="create-document" value="meeting-notes">
                <button type="submit" class="button is-danger">
                    <span class="icon">
                        <i class="fas fa-file-alt"></i>
                    </span>
                    <span>Create Meeting Notes</span>
                </button>
            </form>
            {% endif %}
            {% if user.is_staff and not event.slideshow_id %}
            <a href="?select-slideshow=1" class="button is-warning">
                <span class="icon">
                    <i class="fab fa-slideshare"></i>
                </span>
                <span>Select Slideshow</span>
            </a>
            {% endif %}
            
            {% if not event.has_started and not user.is_staff and not rsvp and show_rsvp_form %}
            {% include "club/events/includes/event_rsvp_modal.html" %}
            {% endif %}
            {% endif %}
            <a href="{% url 'events' %}" class="button is-link">
                <span class="icon">
                    <i class="fas fa-chevron-left"></i>
                </span>
                <span>All Events</span>
            </a>
            <a href="{% url 'event_planning' event.id %}" class="button is-warning">Planning</a>
        </div>
    </div>
</section>
{% endblock %}

club/templates/club/events/index.html
{% extends "club/base.html" %}
{% block head %}
<style>
    .media-body hr {
        margin-top: 10px;
        margin-bottom: 10px;
    }

    .event-summary {
        transition: box-shadow 0.2s;
    }

    .event-summary:hover {
        box-shadow: 0 1em 1em -0.125em rgba(10, 10, 10, 0.1), 0 0px 0 1px rgba(10, 10, 10, 0.02);
    }
</style>
{% endblock %}
{% block content %}
<section class="hero is-primary">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">Club Events</h1>
            <h2 class="subtitle">We host workshops, code jams, speaker sessions and more!</h2>
        </div>
    </div>
</section>
<section class="section event-index">
    <div class="container">
        {% include 'club/includes/messages.html' %}

        <h1 id="upcoming" class="title">
            <a href="#upcoming">Upcoming</a>
        </h1>
        <div class="columns">
            <div class="column is-half">
                {% for event in upcoming_events %}
                <div class="box media event-summary">
                    <div class="media-left">
                        <p class="image is-128x128" style="display: flex; align-items: center;">
                            {% if event.slideshow_id %}
                            <a title="Event slideshow" target="_blank" href="{{ event.slideshow_link }}">
                                <img alt="Thumbail for event slideshow" src="{{ event.thumbnail_link }}">
                            </a>
                            {% endif %}
                        </p>
                    </div>
                    <div class="media-body">
                        <a href="{% url 'event_detail' event.id %}">
                            <h3 class="title is-size-4">
                                {{ event.title }}
                                <span class="has-text-grey">{{ event.get_event_type_display }}</span>
                            </h3>
                        </a>
                        {% if event.tagline %}
                        <h4 class="subtitle"><em>{{ event.tagline }}</em></h4>
                        {% endif %}

                        <i class="far fa-clock"></i>
                        <span class="event-date">{{ event.start|date:"l, F jS" }}</span> | 
                        <span class="event-time">{{ event.start|time:"g:i a" }} - {{ event.end|time:"g:i a" }}</span>
                        <br>
                        <a href="https://maps.google.com/?q={{ event.full_location|urlencode }}"
                            title="This event is being held in {{ event.location }}" target="_blank"
                            class="event-location">
                            <i class="fas fa-map-marker-alt"></i>
                            {{ event.location }}
                        </a>
                        {% if not event.is_publicly_visible %}<span class="icon" title="Not publicily visible"><i class="far fa-eye-slash"></i></span>{% endif %}

                        <hr>
                        {% if user.is_staff %}
                        <div class="tags is-pulled-right">
                            <span class="tag is-dark">{{ event.rsvps.count }} RSVPs</span>
                            <span class="tag is-info">{{ event.attendance.count }} attendees</span>
                        </div>
                        {% endif %}
                        <div class="buttons">
                            {% if not event.has_started %}
                            {% if event in user_rsvped_events %}
                            <a title="You have RSVPed for this event." href="{% url 'event_detail' event.id %}" class="button is-success is-small is-disabled" disabled>
                                <span class="icon">
                                    <i class="fas fa-calendar-check"></i>
                                </span>
                                <span>RSVPed</span>
                            </a>
                            {% elif not user.is_staff %}
                            <a href="{% url 'event_rsvp' event.id %}" class="button is-success is-small">
                                <span class="icon">
                                    <i class="fas fa-calendar-check"></i>
                                </span>
                                <span>RSVP</span>
                            </a>
                            {% endif %}
                            {% endif %}

                            {% if event.is_ongoing and user.is_authenticated and not user.is_staff %}
                            
                            {% if event in user_attended_events %}
                            <a href="{% url 'event_detail' event.id %}" class="button is-small is-warning is-disabled" disabled>
                                <span class="icon">
                                    <i class="fas fa-user-check"></i>
                                </span>
                                <span>Submitted Attendance</span>
                            </a>
                            {% else %}
                            <a href="{% url 'event_attendance' event.id %}" class="button is-small is-warning">
                                <span class="icon">
                                    <i class="fas fa-user-check"></i>
                                </span>
                                <span>Submit Attendance</span>
                            </a>
                            {% endif %}

                            {% endif %}
                            <a href="{% url 'event_detail' event.id %}" class="button is-link is-small">
                                <span class="icon">
                                    <i class="fas fa-info-circle"></i>
                                </span>
                                <span>View</span>
                            </a>
                        </div>
                    </div>
                    <!-- <a class="button is-primary" >View</a> -->
                </div>
                {% empty %}
                <p class="has-text-grey is-size-4">
                    There are no upcoming events yet. Stay tuned!
                </p>
                <br>
                <button title="Coming soon..." class="button is-link is-large" disabled>
                    <span class="icon">
                        <span class="fas fa-plus"></span>
                    </span>
                    <span>Request Event</span>
                </button>
                {% endfor %}
            </div>
            <div class="column is-half">
                <iframe
                    src="https://calendar.google.com/calendar/embed?src={{ google_calendar_id }}&ctz=America%2FNew_York"
                    style="border: 0" width="100%" height="600" frameborder="0" scrolling="no"></iframe>
            </div>
        </div>

        <hr>

        <h2 id="past" class="title is-size-4">
            <a href="#past">Past Events</a>
        </h2>
        {% if past_events|length > 0 %}
        <table class="table is-fullwidth">
            <thead>
                <tr>
                    <th>When</th>
                    <th>Type</th>
                    <th>Title</th>
                    {% if user.is_staff %}
                    <th>Attendance/RSVPs</th>
                    <th>Reviewed?</th>
                    {% endif %}
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for event in past_events %}
                <tr>
                    <td>{{ event.start }}</td>
                    <td>{{ event.get_event_type_display }}</td>
                    <td>
                        {% if not event.is_publicly_visible %}<span class="icon" title="Not publicily visible"><i class="far fa-eye-slash"></i></span>{% endif %}
                        <span>{{ event.title }}</span>
                        {% if event in user_rsvped_events %}
                        <span class="tag is-primary">RSVPed</span>
                        {% endif %}
                        {% if event in user_attended_events %}
                        <span class="tag is-success">Attended</span>
                        {% endif %}
                    </td>
                    {% if user.is_staff %}
                    <td>{{ event.attendance.count }}/{{ event.rsvps.count }}</td>
                    <td>
                        <span class="icon">
                            {% if event.review %}
                            <i class="fas fa-check has-text-success"></i>
                            {% else %}
                            <i class="fas fa-times has-text-danger"></i>
                            {% endif %}
                        </span>
                    </td>
                    {% endif %}
                    <td>
                        <a href="{% url 'event_detail' event.id %}" class="button is-small is-pulled-right">View</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p class="has-text-grey">There are no past events.</p>
        {% endif %}
    </div>
</section>

{% endblock %}